### ISSUE TITLE
Vesión de Python para correr programas

### ISSUE THREAD

**Issue by shirleyah** [ulisesplaper/python_class#6]
@ulisesplaper me podrías decir cuál versión de **python** utilizar para correr los scripts?

**Comment by ulisesplaper** [comment]
Claro, es Python 3.10.2

**Comment by ulisesplaper** [comment]
@Helysalgado podrias ayudarme con el issue?

**Comment by Helysalgado** [comment]
corroboro la versión @ulisesplaper
